/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20 } from "./ERC20";
export type { IERC165 } from "./IERC165";
export type { IERC20 } from "./IERC20";
export type { IERC20Metadata } from "./IERC20Metadata";
export type { IERC721 } from "./IERC721";
export type { IERC721Metadata } from "./IERC721Metadata";
export type { IERC721Receiver } from "./IERC721Receiver";
export type { WAVEBar } from "./WAVEBar";
export type { Ve } from "./Ve";
