/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface IRewarderInterface extends utils.Interface {
  functions: {
    "onWAVEReward(uint256,address,address,uint256,uint256)": FunctionFragment;
    "pendingTokens(uint256,address,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "onWAVEReward" | "pendingTokens"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "onWAVEReward",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingTokens",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "onWAVEReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingTokens",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IRewarder extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IRewarderInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    onWAVEReward(
      pid: PromiseOrValue<BigNumberish>,
      user: PromiseOrValue<string>,
      recipient: PromiseOrValue<string>,
      waveAmount: PromiseOrValue<BigNumberish>,
      newLpAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    pendingTokens(
      pid: PromiseOrValue<BigNumberish>,
      user: PromiseOrValue<string>,
      waveAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string[], BigNumber[]]>;
  };

  onWAVEReward(
    pid: PromiseOrValue<BigNumberish>,
    user: PromiseOrValue<string>,
    recipient: PromiseOrValue<string>,
    waveAmount: PromiseOrValue<BigNumberish>,
    newLpAmount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  pendingTokens(
    pid: PromiseOrValue<BigNumberish>,
    user: PromiseOrValue<string>,
    waveAmount: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<[string[], BigNumber[]]>;

  callStatic: {
    onWAVEReward(
      pid: PromiseOrValue<BigNumberish>,
      user: PromiseOrValue<string>,
      recipient: PromiseOrValue<string>,
      waveAmount: PromiseOrValue<BigNumberish>,
      newLpAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    pendingTokens(
      pid: PromiseOrValue<BigNumberish>,
      user: PromiseOrValue<string>,
      waveAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string[], BigNumber[]]>;
  };

  filters: {};

  estimateGas: {
    onWAVEReward(
      pid: PromiseOrValue<BigNumberish>,
      user: PromiseOrValue<string>,
      recipient: PromiseOrValue<string>,
      waveAmount: PromiseOrValue<BigNumberish>,
      newLpAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    pendingTokens(
      pid: PromiseOrValue<BigNumberish>,
      user: PromiseOrValue<string>,
      waveAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    onWAVEReward(
      pid: PromiseOrValue<BigNumberish>,
      user: PromiseOrValue<string>,
      recipient: PromiseOrValue<string>,
      waveAmount: PromiseOrValue<BigNumberish>,
      newLpAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    pendingTokens(
      pid: PromiseOrValue<BigNumberish>,
      user: PromiseOrValue<string>,
      waveAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
